# Datenbereinigung und Vorbereitung

author: "Zhanna Davtyan"

***Hinweis:*** führen Sie dieses Notebook aus, nachdem Sie das `01 Daten Laden` Notebook ausgeführt haben, um die erforderlichen Metadaten zu generieren.

In [12]:
import pandas as pd
import numpy as np
import os

### Daten aus pickle Dateien laden

In [13]:
df = pd.read_pickle("ergebnisse/instagram_node_dataframe.pkl")
df.head()

,post_number,folder_name,__typename,id,gating_info,fact_check_overall_rating,fact_check_information,media_overlay_info,sensitivity_friction_info,display_url,...,location.has_public_page,location.name,location.slug,edge_sidecar_to_children.edges,has_upcoming_event,location,nft_asset_info,coauthor_producers,pinned_for_users,edge_liked_by.count
0,1,kayaancontractor_100226_2868439159916464863_205_2,GraphSidecar,2868439159916464863,None,None,None,None,NaN,https://instagram.fbom3-2.fna.fbcdn.net/v/t51....,...,True,"Mumbai, Maharashtra",mumbai-maharashtra,"[{'node': {'__typename': 'GraphImage', 'id': '...",NaN,NaN,NaN,NaN,NaN,NaN
1,2,debasreee_307029_3066886135067171352_7650_20,GraphSidecar,3066886135067171352,None,None,None,None,NaN,https://instagram.fbom3-1.fna.fbcdn.net/v/t51....,...,NaN,NaN,NaN,"[{'node': {'__typename': 'GraphImage', 'id': '...",False,NaN,NaN,[],[],7650.0
2,3,shereenlovebug_333413_3029832820659598377_456_27,GraphSidecar,3029832820659598377,None,None,None,None,NaN,https://instagram.fbom19-1.fna.fbcdn.net/v/t51...,...,NaN,NaN,NaN,"[{'node': {'__typename': 'GraphImage', 'id': '...",NaN,NaN,NaN,NaN,NaN,NaN
3,4,mandirabedi_2034192_2889470489057495466_9167_86,GraphSidecar,2889470489057495466,None,None,None,None,NaN,https://scontent-bom1-1.cdninstagram.com/v/t51...,...,NaN,NaN,NaN,"[{'node': {'__typename': 'GraphImage', 'id': '...",NaN,NaN,NaN,NaN,NaN,NaN
4,5,rahulkl_130314_3053766391959056433_4057_18,GraphImage,3053766391959056433,None,None,None,None,NaN,https://instagram.fbom19-2.fna.fbcdn.net/v/t51...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Datenaufbereitung für die Analyse
Hier werden für die Analyse relevante Daten aufbereitet und passendere Spaltennamen vergeben. 

Im df_gefiltert Dataframe enthält die wichtigsten Spalten, die einen Einfluss auf Likeanzahl haben könnten.

In [5]:
df_gefiltert = df.rename(columns={
    "edge_media_preview_like.count": "likes",
    "owner.edge_followed_by.count": "follower_count",
    "owner.is_verified": "is_verified",
    "owner.category_name": "account_category",
    "owner.is_business_account": "is_business_account",
    "owner.is_professional_account": "is_professional_account",
    "edge_media_to_comment.count": "comment_count",
    "edge_media_to_tagged_user.edges": "tagged_users",
    "edge_media_to_caption.edges": "caption_text",
    "__typename": "post_type",
    "edge_sidecar_to_children.edges": "is_carousel",
    "taken_at_timestamp": "timestamp",
    "folder_name": "post_id"
    })

df_gefiltert = df_gefiltert[[
    "likes",
    "follower_count",
    "is_verified",
    "account_category",
    "is_business_account",
    "is_professional_account",
    "comment_count",
    "tagged_users",
    "caption_text",
    "post_type",
    "is_carousel",
    "timestamp",   
    "post_id"
]]
df_gefiltert.head()

,likes,follower_count,is_verified,account_category,is_business_account,is_professional_account,comment_count,tagged_users,caption_text,post_type,is_carousel,timestamp,post_id
0,205,100226,True,Digital creator,False,True,2,[{'node': {'user': {'full_name': 's h a p e s ...,[{'node': {'text': '“Got your nose!”🫶🏻 #caturd...,GraphSidecar,"[{'node': {'__typename': 'GraphImage', 'id': '...",1656164616,kayaancontractor_100226_2868439159916464863_205_2
1,7650,307029,True,Blogger,False,True,20,[{'node': {'user': {'full_name': 'summer somew...,[{'node': {'text': 'Dreaming of this as I have...,GraphSidecar,"[{'node': {'__typename': 'GraphImage', 'id': '...",1679821339,debasreee_307029_3066886135067171352_7650_20
2,456,333413,True,Digital creator,False,True,27,[{'node': {'user': {'full_name': 'Dior Beauty ...,[{'node': {'text': '@diorbeauty forever 🖤 . . ...,GraphSidecar,"[{'node': {'__typename': 'GraphImage', 'id': '...",1675404239,shereenlovebug_333413_3029832820659598377_456_27
3,9167,2034192,True,Actor,False,True,86,[],[{'node': {'text': 'And that’s how you eat a s...,GraphSidecar,"[{'node': {'__typename': 'GraphImage', 'id': '...",1658671745,mandirabedi_2034192_2889470489057495466_9167_86
4,4057,130314,False,Fan page,False,True,18,"[{'node': {'user': {'full_name': 'KL Rahul👑', ...",[{'node': {'text': 'Happy Holi everyone 😆❤️💚💜 ...,GraphImage,NaN,1678257343,rahulkl_130314_3053766391959056433_4057_18

In [6]:
df_gefiltert.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1968 entries, 0 to 1967
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   likes                    1968 non-null   int64
 1   follower_count           1968 non-null   int64
 2   is_verified              1968 non-null   bool
 3   account_category         1766 non-null   object
 4   is_business_account      1968 non-null   bool
 5   is_professional_account  1968 non-null   bool
 6   comment_count            1968 non-null   int64
 7   tagged_users             1968 non-null   object
 8   caption_text             1968 non-null   object
 9   post_type                1968 non-null   object
 10  is_carousel              1006 non-null   object
 11  timestamp                1968 non-null   int64
 12  post_id                  1968 non-null   object
dtypes: bool(3), int64(4), object(6)
memory usage: 159.6+ KB

### Vorbereitung

#### Zielvariable: Likes

Die Rohdaten der "Likes"-Anzahl weisen oft Eigenschaften auf (z.B. extreme Schiefe, Ausreißer), die statistische Analysen oder die Leistung von Machine-Learning-Modellen beeinträchtigen können. Ziel der folgenden Schritte ist es, die Datenqualität zu verbessern und die Variable für nachfolgende Analysen zu optimieren.

- Negative Werte behandeln
    - Alle Werte kleiner als 0 werden auf 0 gesetzt
    - "Likes" sind Zählwerte und können logischerweise nicht negativ sein. Dieser Schritt korrigiert mögliche fehlerhafte negative Einträge.

-  Log-Transformation
    - Die Log-Transformation dient dazu, die statistischen Eigenschaften der Gesamtheit der Daten zu verbessern und sie für die Modellierung oder bestimmte Analysen geeigneter zu machen. Sie zielt darauf ab, Muster und Beziehungen aufzudecken, die in den Rohdaten durch die Schiefe oder Ausreißer verdeckt sein könnten.
    ```python
    np.log1p(x) ≡ np.log(1 + x)
    ```             
    um, log(0)= -∞ zu vermeiden

In [7]:
df_gefiltert['likes'] = df_gefiltert['likes'].clip(lower=0).astype(int)
# Log-Transformation der Likes
df_gefiltert['likes_log'] = np.log1p(df_gefiltert['likes'])
print("\n'likes_log' Spalte erstellt.")
df_gefiltert[['likes_log', 'likes']]

'likes_log' Spalte erstellt.

      likes_log    likes
0      5.327876      205
1      8.942592     7650
2      6.124683      456
3      9.123474     9167
4      8.308446     4057
...         ...      ...
1963   0.000000        0
1964   9.292013    10850
1965   8.758884     6366
1966  15.311659  4464459
1967   8.268219     3897

[1968 rows x 2 columns]

Zeitbasierte Merkmale

In [8]:
df_gefiltert['datetime'] = pd.to_datetime(df_gefiltert['timestamp'], unit='s')
df_gefiltert['hour_of_day'] = df_gefiltert['datetime'].dt.hour
df_gefiltert['day_of_week'] = df_gefiltert['datetime'].dt.day_of_week + 1
df_gefiltert['month'] = df_gefiltert['datetime'].dt.month
      
print("\nZeitbasierte Merkmale erstellt.")
df_gefiltert[['datetime', 'hour_of_day', 'day_of_week', 'month']].head()

Zeitbasierte Merkmale erstellt.

             datetime  hour_of_day  day_of_week  month
0 2022-06-25 13:43:36           13            6      6
1 2023-03-26 09:02:19            9            7      3
2 2023-02-03 06:03:59            6            5      2
3 2022-07-24 14:09:05           14            7      7
4 2023-03-08 06:35:43            6            3      3

caption_text Extraktion

In [9]:
def extract_caption(edges):
    if isinstance(edges, list) and len(edges) > 0 and 'node' in edges[0] and 'text' in edges[0]['node']:
        return edges[0]['node']['text']
    return "" 

df_gefiltert['actual_caption_text'] = df_gefiltert['caption_text'].apply(extract_caption)
df_gefiltert['caption_length'] = df_gefiltert['actual_caption_text'].apply(len)
df_gefiltert['hashtag_count'] = df_gefiltert['actual_caption_text'].str.count('#')
df_gefiltert['mention_count'] = df_gefiltert['actual_caption_text'].str.count('@')

df_gefiltert[['actual_caption_text', 'caption_length', 'hashtag_count', 'mention_count']].head()

,actual_caption_text,caption_length,hashtag_count,mention_count
0,“Got your nose!”🫶🏻 #caturday \n.\n#saturday #l...,111,7,0
1,Dreaming of this as I have the laziest Sunday ...,136,0,4
2,@diorbeauty forever 🖤\n.\n.\n.\n\n⁣\n.⁣\n.⁣\n....,232,14,1
3,And that’s how you eat a s’more !! \n#marshmel...,58,2,0
4,Happy Holi everyone 😆❤️💚💜\n\nHas v liya karro ...,52,0,1

Karussell-Informationen

In [10]:
def check_carousel_and_count(edges):
    if isinstance(edges, list) and len(edges) > 0:
        return True, len(edges) # Ist Karussell, Anzahl der Medien
    return False, 1 # Kein Karussell (oder einzelnes Medium)

results = df_gefiltert['is_carousel'].apply(lambda x: check_carousel_and_count(x)) 
df_gefiltert['is_carousel_bool'] = [res[0] for res in results]
df_gefiltert['media_count_in_post'] = [res[1] for res in results]

# Für Nicht-Karussell-Posts ('GraphImage', (kein 'GraphSidecar/Karusell')) ist media_count_in_post typischerweise 1
df_gefiltert.loc[df_gefiltert['post_type'] != 'GraphSidecar', 'media_count_in_post'] = 1
df_gefiltert.loc[df_gefiltert['post_type'] != 'GraphSidecar', 'is_carousel_bool'] = False

df_gefiltert[['is_carousel_bool', 'media_count_in_post']].head()

   is_carousel_bool  media_count_in_post
0              True                    3
1              True                    4
2              True                    5
3              True                    6
4             False                    1

### Verarbeitete Daten für die spätere Verwendung speichern

In [11]:
os.makedirs("ergebnisse", exist_ok=True)

# DataFrame im "ergebnisse"-Ordner speichern
df_gefiltert.to_pickle("ergebnisse/verarbeitete_daten.pkl")